# --- !Ups

create table Regime (
    code varchar(255) not null,
    nom varchar(255),
    adresse varchar(500),
    tel varchar(255),
    site varchar(500),
    primary key(code)
);

insert into Regime (code, nom, adresse, tel, site) values('0068','Caisses des régimes de retraite complémentaire','<p><a href="http://www.agirc-arrco.fr/particuliers/utiles-particuliers/annuaire-des-caisses-de-retraite/" target="_blank" title="coordonnées des caisses AGIRC ARRCO"><u>Coordonn&eacute;es des caisses agirc arrco</u></a></p>','<p style="line-height: 20.8px;">0 820 200 189&nbsp;</p><p style="line-height: 20.8px;">(Num&eacute;ro Indigo : 0,09 euro /min)</p>','<p><a href="http://www.agirc-arrco.fr" target="_blank" title="http://www.agirc-arrco.fr">www.agirc-arrco.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('2223','Caisse de retraite de la banque de france','<p>Service des Pensions&nbsp;<br />77431 Marne la Vall&eacute;e Cedex 2</p>','<p>01 64 80 21 69</p>','<p><a href="http://www.retraite.banque-france.fr/" target="_blank" title="www.retraite.banque-france.fr/">www.retraite.banque-france.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1158','Caisse autonome de retraite des chirurgiens dentistes','<p>50, avenue Hoche<br />75381 Paris Cedex 08</p>','<p>01 40 55 42 29</p>','<p><a href="http://www.carcdsf.fr/index.php/chirurgiens-dentistes" target="_blank" title="Accéder au site www.carcdsf.fr (lien ouvrant sur une nouvelle fenêtre)">chirurgiens-dentistes</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1037','Caisse autonome de retraite des médecins de France','<p>46, rue Saint-Ferdinand<br />75 841 Paris Cedex 17</p>','<p>01 40 68 32 00</p>','<p><a href="http://www.carmf.fr" target="_blank" title="http://www.carmf.fr">www.carmf.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1036','Caisse autonome de retraite et de prévoyance des infirmiers, masseurs, kinésitherapeutes, podologues, orthophonistes, orthoptistes','<p>6 place Charles-de-Gaulle<br />78882 - Saint-Quentin-en-Yvelines Cedex</p>','<p>01 30 48 10 00</p>','<p><a href="http://www.carpimko.fr" target="_blank" title="http://www.carpimko.fr">www.carpimko.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1155','Caisse autonome de retraite et de prévoyance des vétérinaires','<p>64, avenue Raymond Poincar&eacute;<br />75116 Paris</p>','<p>01 47 70 72 53</p>','<p><a href="http://www.carpv.fr" target="_blank" title="http://www.carpv.fr">www.carpv.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1154','Caisse autonome de retraite des sages-femmes françaises','<p>50, avenue Hoche<br />75381 Paris Cedex 08</p>','<p>01 40 55 42 29</p>','<p><a href="http://www.carcdsf.fr/index.php/sages-femmes" target="_blank" title="Accéder au site www.carcdsf.fr (lien ouvrant sur une nouvelle fenêtre)">sages-femmes</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1033','Caisse d''allocation vieillesse des agents généraux et des mandataires non salariés de l''assurance et de la capitalisation','<p>30, rue Olivier Noyer&nbsp;<br />CS n&deg; 51432 75676&nbsp;<br />Paris cedex 14</p>','<p>01 81 69 36 01</p>','<p><a href="http://www.cavamac.fr" target="_blank" title="http://www.cavamac.fr">www.cavamac.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1034','Caisse d''assurance vieillesse des experts comptables et des commissaires aux comptes','<p>48 bis rue Fabert<br /><span style="line-height: 20.7999992370605px;">TSA 80711</span><br /><span style="line-height: 20.7999992370605px;">75329 Paris cedec 07</span></p>','<p><span style="line-height: 20.7999992370605px;">01 80 49 25 25</span></p>','<p><a href="http://www.cavec.fr" target="_blank" title="http://www.cavec.fr">www.cavec.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0263','Caisse d''assurance vieillesse invalidité et maladie des cultes','<p>&quot;Le Tryalis&quot;<br />9, rue de Rosny<br />93100 Montreuil sous Bois</p>','<p>01 41 58 45 45&nbsp;</p>','<p><a href="http://www.cavimac.fr" target="_blank" title="http://www.cavimac.fr">www.cavimac.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1152','Caisse d''assurance vieillesse des officiers ministeriels, des officiers publics et des compagnies judiciaires','<p>9, rue de Vienne</p><p>75 403 Paris Cedex 08&nbsp;</p>','<p>01 44 95 68 00&nbsp;</p>','<p><a href="http://www.cavom.fr" target="_blank" title="http://www.cavom.fr">www.cavom.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1153','Caisse d''assurance vieillesse des pharmaciens','<p>45, rue Caumartin&nbsp;<br />75 441 Paris Cedex 09&nbsp;</p>','<p>01 42 66 90 37</p>','<p><a href="http://www.cavp.fr" target="_blank" title="http://www.cavp.fr">www.cavp.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0017','Caisse centrale de la mutualité sociale agricole','<p><a href="http://www.msa.fr/lfr/contact/coordonnees-msa" style="line-height: 20.8px;" target="_blank" title="Coordonnées des MSA"><u>Les coordonn&eacute;es des MSA</u></a></p>','<p><a href="http://www.msa.fr/lfr/contact/coordonnees-msa" style="line-height: 20.8px;" target="_blank" title="Coordonnées des MSA"><u>Les coordonn&eacute;es des MSA</u></a></p>','<p><a href="http://www.msa.fr/" target="_blank" title="http://www.msa.fr">www.msa.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('2295','Régime des exploitants non salariés agricoles','<p><a href="http://www.msa.fr/lfr/contact/coordonnees-msa" target="_blank" title="Coordonnées des MSA"><u>Les coordonn&eacute;es des MSA</u></a></p>','<p><a href="http://www.msa.fr/lfr/contact/coordonnees-msa" style="line-height: 20.8px;" target="_blank" title="Coordonnées des MSA"><u>Les coordonn&eacute;es des MSA</u></a></p>','<p><a href="http://www.msa.fr" target="_blank" title="http://www.msa.fr">www.msa.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('2294','Régime des salariés agricoles','<p><a href="http://www.msa.fr/lfr/contact/coordonnees-msa" style="line-height: 20.8px;" target="_blank" title="Coordonnées des MSA"><u>Les coordonn&eacute;es des MSA</u></a></p>','<p><a href="http://www.msa.fr/lfr/contact/coordonnees-msa" style="line-height: 20.8px;" target="_blank" title="Coordonnées des MSA"><u>Les coordonn&eacute;es des MSA</u></a></p>','<p><a href="http://www.msa.fr" target="_blank" title="http://www.msa.fr">www.msa.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1038','Caisse interprofessionnelle de prévoyance et d''assurance vieillesse','<p>9 rue de Vienne<br />75 403 Paris Cedex 08&nbsp;</p>','<p>01 44 95 68 20 (service cotisation)<br />01 44 95 68 49 (Service prestation)</p>','<p><a href="http://www.cipav-retraite.fr/" title="http://www.agirc-arrco.fr">www.cipav-retraite.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0018','Caisse nationale d''assurance vieillesse','<p><u><a href="https://www.lassuranceretraite.fr/portail-info/home/salaries/nos-contacts.html" target="_blank">Coordonn&eacute;es de votre caisse r&eacute;gionale</a></u></p>','<p>39 60&nbsp;&nbsp;(prix d&#39;un appel local depuis un poste fixe)</p><p><span style="line-height: 20.8px;">09 71 10 39 60 (d</span>epuis l&#39;&eacute;tranger, une box ou&nbsp;un mobile)</p>','<p><a href="http://www.lassuranceretraite.fr/" target="_blank" title="www.lassuranceretraite.fr/">www.lassuranceretraite.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1157','Caisse nationale des barreaux francais','<p>11, boulevard de S&eacute;bastopol&nbsp;<br />75 038 Paris Cedex 01</p>','<p>01 42 21 32 30</p>','<p><a href="http://www.cnbf.fr" target="_blank" title="http://www.cnbf.fr">www.cnbf.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0067','Caisse nationale des industries électriques et gazières','<p>20, rue des Fran&ccedil;ais Libres</p><p>CS 60415</p><p>44204 Nantes Cedex 2</p>','<p>02 40 84 01 84</p>','<p><a href="http://www.cnieg.fr/" target="_blank" title="http://www.cnieg.fr/">www.cnieg.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0066','Caisse nationale des régimes des agents des collectivités locales','<p>Rue du Vergne&nbsp;<br />33 059 Bordeaux Cedex</p>','','<p><a href="https://www.cnracl.fr" target="_blank" title="https://www.cnracl.fr">www.cnracl.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0065','Caisse de prévoyance et de retraite de la SNCF','<p>17, avenue du G&eacute;n&eacute;ral Leclerc<br />13320&nbsp;Marseille Cedex 20</p>','<p>04 95 04 04 04</p>','<p><a href="http://www.cprpsncf.fr/" target="_blank" title="accédez au site de la CPRPSNCF (lien ouvrant sur une nouvelle fenêtre)">http://www.cprpsncf.fr/</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0073','Régie autonome des transports parisiens','<p>201, rue Carnot<br />94127 Fontenay-sous-Bois Cedex</p>','<p>01 49 74 72 20</p>','<p><a href="http://www.crpratp.fr/" target="_blank" title="Accédez au site de la CRP RATP (lien ouvrant sur une nouvelle fenêtre)">www.crpratp.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1151','Caisse de retraite des notaires','<p>43, avenue Hoche&nbsp;<br />75 008 Paris</p>','<p>01 53 81 75 00&nbsp;</p>','<p><a href="http://www.crn.fr/" target="_blank" title="Accéder au site www.crn.fr (lien ouvrant sur une nouvelle fenêtre)">www.crn.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0090','Comédie française','<p>182 rue de Rivoli<br />75001 Paris</p>','<p>01 44 58 14 14&nbsp;</p>','');
insert into Regime (code, nom, adresse, tel, site) values('2142','Caisse de retraite du personnel navigant professionnel de l''aéronautique civile','<p>8, rue de l&#39;H&ocirc;tel de Ville&nbsp;<br />92 522 Neuilly sur Seine Cedex&nbsp;</p>','<p>01 41 92 25 25&nbsp;</p>','<p><a href="http://www.crpn.fr/" target="_blank" title="Accédez au site de la CRPN (lien ouvrant sur une nouvelle fenêtre)">www.crpn.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0106','Caisse de retraite des personnels de l''opéra national de Paris','<p>73, boulevard Haussmann<br />75008 Paris&nbsp;</p>','<p>01 47 42 72 08</p>','<p><a href="http://www.caisse-de-retraite-opera-de-paris.fr/" target="_blank" title="Accédez au site de la Caisse de retraites des personnels de l''Opéra national de Paris (lien ouvrant sur une nouvelle fenêtre)">w</a><a href="http://www.cropera.fr/" target="_blank" title="www.cropera.fr/">ww.cropera.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0089','Caisse de retraite et de prévoyance des clercs et employés de notaires','<p>5 bis rue de Madrid&nbsp;<br />75395 PARIS CEDEX 08</p>','<p>01 44 90 20 81</p>','<p><a href="https://www.crpcen.fr/" target="_blank" title="Accédez au site de la CRPCEN (lien ouvrant sur une nouvelle fenêtre)">www.crpcen.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('1041','Etablissement national des invalides de la marine','<p>Centre des pensions&nbsp;</p><p>1 bis rue Pierre Loti&nbsp;<br />BP 240 22505 PAIMPOL CEDEX&nbsp;</p>','<p>02 96 55 32 32</p>','<p><a href="http://www.enim.eu/" target="_blank" title="Accédez au site de l''ENIM (lien ouvrant sur une nouvelle fenêtre)">www.enim.eu</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0078','Fonds spécial des pensions des ouvriers des établissements industriels de l''Etat','<p>Rue du Vergne<br />33059 Bordeaux Cedex</p>','','<p><a href="http://www.fspoeie.fr/" target="_blank" title="Accéder au site www.fspoeie.fr (lien ouvrant sur une nouvelle fenêtre)">www.fspoeie.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0069','Institution retraite complémentaire des agents non titulaires de l''état et des collectivités publiques','<p>24, rue Louis Gain 49939 Angers cedex 9</p>','<p>02 41 05 25 25</p>','<p><a href="https://www.cdc.retraites.fr/portail/spip.php?page=rubrique&amp;id_rubrique=256#pos" target="_blank" title="Accédez au site de l''IRCANTEC (lien ouvrant sur une nouvelle fenêtre)">www.ircantec.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('2139','Institution de retraite complémentaire de l’enseignement et de la création','<p>9 rue de Vienne<br />75008 Paris&nbsp;</p>','<p>Pour les cotisants : 01.44.95.68.30</p><p>Pour les retrait&eacute;s : 01.44.95.68.31</p>','<p><a href="http://www.ircec.fr" target="_blank" title="http://www.ircec.fr">www.ircec.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0075','Ccaisse de retraite des mines','<p>Caisse des D&eacute;p&ocirc;ts<br />Direction des retraites - Etablissement de Paris<br />Retraite des Mines<br />TSA N&deg;61348</p><p>75914 Paris cedex 13&nbsp;</p>','<p>01 58 50 27 09</p>','<p><a href="http://retraitesolidarite.caissedesdepots.fr/retraite-des-mines" target="_blank" title="Accédez au site Retraite des Mines (lien ouvrant sur une nouvelle fenêtre)">retraitesolidarite.caissedesdepots.fr/retraite-des-mines</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0472','Port autonome de Strasbourg','<p>25 rue de la Nu&eacute;e Bleue<br />BP 407 R/2<br />67002 Strasbourg Cedex</p>','<p>03 88 21 74 09</p>','');
insert into Regime (code, nom, adresse, tel, site) values('2141','Etablissement de retraite additionnelle de la fonction publique','<p>Rue du Vergne<br />33 059 Bordeaux Cedex</p>','<p>02 41 05 30 15</p>','<p><a href="http://www.rafp.fr/" target="_blank" title="Accéder au site www.rafp.fr (lien ouvrant sur une nouvelle fenêtre)">www.rafp.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('3029','Régime complémentaire des indépendants','<p>260-264, avenue du Pr&eacute;sident Wilson<br />93457 La-Plaine-Saint-Denis Cedex</p>','<p>01 77 93 00 00</p>','<p><a href="http://www.rsi.fr/" target="_blank" title="Accédez au site www.rsi.fr (lien ouvrant sur une nouvelle fenêtre)">www.rsi.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0070','Retraite de base des artisans','<p>260-264, avenue du Pr&eacute;sident Wilson<br />93 457 La-Plaine-Saint-Denis Cedex</p>','<p>01 77 93 00 00</p>','<p><a href="http://www.rsi.fr/" target="_blank" title="Accédez au site www.rsi.fr (lien ouvrant sur une nouvelle fenêtre)">www.rsi.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0071','Retraite de base des commerçants et industriels','<p>260-264, avenue du Pr&eacute;sident Wilson<br />93457 La-Plaine-Saint-Denis Cedex</p>','<p>01 77 93 00 00</p>','<p><a href="http://www.rsi.fr/" target="_blank" title="Accédez au site www.rsi.fr (lien ouvrant sur une nouvelle fenêtre)">www.rsi.fr</a></p>');
insert into Regime (code, nom, adresse, tel, site) values('0074','Service des retraites de l''Etat','<p>10, Boulevard Gaston Doumergue&nbsp;<br />44964 Nantes Cedex 9</p>','<p>Fonctionnaires en activit&eacute; : 02 40 08 87 65<br />Retrait&eacute;s et pensionn&eacute;s : 0 810 10 33 35</p>','<p><a href="http://retraitesdeletat.gouv.fr/" target="_blank" title="retraitesdeletat.gouv.fr">retraitesdeletat.gouv.fr</a></p>');


# --- !Downs

DROP TABLE Regime; 